/**
 * generate-bundle.ts
 * Scans all SKILL.md files from src/bundled/ and generates
 * src/bundled-data.generated.ts with all skill data inlined as TypeScript.
 * This file is then bundled into dist/hivecrypto.js so skills load without FS access.
 *
 * Usage: bun packages/skills/scripts/generate-bundle.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { YAML } from "bun";

const BUNDLED_DIR = path.join(import.meta.dir, "../src/bundled");
const OUTPUT_FILE = path.join(import.meta.dir, "../src/bundled-data.generated.ts");

interface SkillEntry {
  name: string;
  description: string;
  category: string;
  version: string;
  tools: string[];
  triggers: string[];
  body: string;
}

function parseFrontmatter(content: string): { frontmatter: Record<string, unknown>; body: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { frontmatter: {}, body: content };
  try {
    const frontmatter = YAML.parse(match[1]!) as Record<string, unknown>;
    return { frontmatter, body: match[2]! };
  } catch {
    return { frontmatter: {}, body: content };
  }
}

function scanDir(dir: string): SkillEntry[] {
  const skills: SkillEntry[] = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const entryPath = path.join(dir, entry.name);
    const skillMdPath = path.join(entryPath, "SKILL.md");

    if (fs.existsSync(skillMdPath)) {
      const content = fs.readFileSync(skillMdPath, "utf-8");
      const { frontmatter, body } = parseFrontmatter(content);

      skills.push({
        name: (frontmatter.name as string) ?? entry.name,
        description: (frontmatter.description as string) ?? "",
        category: (frontmatter.category as string) ?? "general",
        version: String(frontmatter.version ?? "1.0.0"),
        tools: (frontmatter.tools as string[]) ?? [],
        triggers: (frontmatter.triggers as string[]) ?? [],
        body,
      });
    } else {
      // Category directory — recurse one level
      skills.push(...scanDir(entryPath));
    }
  }

  return skills;
}

const skills = scanDir(BUNDLED_DIR);

const lines: string[] = [
  "// AUTO-GENERATED by packages/skills/scripts/generate-bundle.ts",
  "// Do NOT edit manually — run `bun packages/skills/scripts/generate-bundle.ts` to regenerate",
  "",
  "export interface BundledSkillEntry {",
  "  name: string;",
  "  description: string;",
  "  category: string;",
  "  version: string;",
  "  tools: string[];",
  "  triggers: string[];",
  "  body: string;",
  "}",
  "",
  `export const BUNDLED_SKILLS_DATA: BundledSkillEntry[] = [`,
];

for (const skill of skills) {
  // Escape backticks and template literal delimiters in body content
  const escapedBody = skill.body.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  const escapedDescription = skill.description.replace(/\\/g, "\\\\").replace(/`/g, "\\`");

  lines.push(`  {`);
  lines.push(`    name: ${JSON.stringify(skill.name)},`);
  lines.push(`    description: \`${escapedDescription}\`,`);
  lines.push(`    category: ${JSON.stringify(skill.category)},`);
  lines.push(`    version: ${JSON.stringify(skill.version)},`);
  lines.push(`    tools: ${JSON.stringify(skill.tools)},`);
  lines.push(`    triggers: ${JSON.stringify(skill.triggers)},`);
  lines.push(`    body: \`${escapedBody}\`,`);
  lines.push(`  },`);
}

lines.push(`];`);
lines.push(``);

fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");

console.info(`[generate-bundle] ✅ Generated ${skills.length} skills → ${path.relative(process.cwd(), OUTPUT_FILE)}`);
