/**
 * routes/artifacts — serves artifact binaries (images generated by MCP
 * tools, screenshots, etc.) created by artifacts/store.ts's createArtifact().
 *
 * Follows the same shape as routes/meeting.ts's handleDownloadMeetingReport:
 * resolve metadata, stream the file from disk with the right Content-Type.
 * Hive is single-tenant behind one bearer token (see startGateway's
 * HIVE_AUTH_TOKEN gate) — same as meeting downloads, no per-user ownership
 * check is layered on top here; inspectArtifact still enforces expiry and
 * that the file on disk matches its recorded hash/size.
 */

import { logger } from "../../utils/logger";
import { col } from "../../storage/hive";
import type { ArtifactDoc } from "../../storage/collections";
import { inspectArtifact } from "../../artifacts/store";

const log = logger.child("routes/artifacts");

type CorsHelper = (r: Response, req: Request) => Response;

export async function handleDownloadArtifact(
  req: Request,
  addCorsHeaders: CorsHelper,
  artifactId: string,
): Promise<Response> {
  try {
    const meta = await inspectArtifact(artifactId);
    if (!meta.ok) {
      return addCorsHeaders(Response.json(meta, { status: 404 }), req);
    }

    const artifactsCol = await col<ArtifactDoc>("artifacts");
    const entry = await artifactsCol.get(artifactId);
    if (!entry) {
      return addCorsHeaders(Response.json({ ok: false, error: "Artifact not found" }, { status: 404 }), req);
    }

    const file = Bun.file(entry.doc.path);
    if (!(await file.exists())) {
      return addCorsHeaders(Response.json({ ok: false, error: "Artifact binary is missing" }, { status: 404 }), req);
    }

    return addCorsHeaders(
      new Response(file, {
        headers: {
          "Content-Type": entry.doc.mime_type,
          "Cache-Control": "private, max-age=3600",
        },
      }),
      req,
    );
  } catch (error) {
    log.error(`handleDownloadArtifact: ${(error as Error).message}`);
    return addCorsHeaders(
      Response.json({ ok: false, error: (error as Error).message }, { status: 500 }),
      req,
    );
  }
}
