// Auto-generated — DO NOT EDIT
// Generated by packages/cli/scripts/generate-ui-bundle.ts — córrelo antes de
// compilar el binario standalone (`bun run build:binary` ya lo hace).
//
// Lo que se commitea es SIEMPRE este stub vacío. El archivo está trackeado
// porque `commands/gateway.ts` lo importa de forma estática y un checkout
// limpio tiene que typecheckear, pero una versión poblada nunca debe entrar al
// repo: quedó commiteada una de 2.99 MB / 90 archivos el 2026-07-03 y durante
// un mes la imagen Docker sirvió esa UI en vez de la que construye en cada
// build. `.github/workflows/ci.yml` falla si vuelve a llegar poblado.
export const embeddedUI = new Map<string, { data: Buffer; mime: string }>([
]);
