#!/usr/bin/env bun
// Generates src/ui-bundle.generated.ts by embedding all files from packages/hive-ui/dist/
// Run before compiling the standalone binary: bun scripts/generate-ui-bundle.ts

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import * as path from "node:path";

const MIME: Record<string, string> = {
  ".html": "text/html",
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".css": "text/css",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
  ".json": "application/json",
  ".txt": "text/plain",
  ".webp": "image/webp",
  ".gif": "image/gif",
  // El avatar 3D de HiveLive. Sin esta entrada se servía como
  // application/octet-stream: el loader lo acepta igual porque detecta el
  // formato por la cabecera del archivo, pero declararlo evita sorpresas con
  // caches y proxies intermedios.
  ".glb": "model/gltf-binary",
};

function walk(dir: string, base = dir): Array<{ sub: string; full: string }> {
  const results: Array<{ sub: string; full: string }> = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...walk(full, base));
    } else {
      const sub = "/" + path.relative(base, full).replace(/\\/g, "/");
      results.push({ sub, full });
    }
  }
  return results;
}

const uiDist = path.join(import.meta.dir, "../../hive-ui/dist");
const outFile = path.join(import.meta.dir, "../src/ui-bundle.generated.ts");

let files: Array<{ sub: string; full: string }>;
try {
  files = walk(uiDist);
} catch {
  console.error(`❌ UI dist not found at ${uiDist}`);
  console.error("   Run: cd packages/hive-ui && bun run build");
  process.exit(1);
}

if (files.length === 0) {
  console.error(`❌ No files found in ${uiDist}`);
  process.exit(1);
}

const entries = files.map(({ sub, full }) => {
  const b64 = readFileSync(full).toString("base64");
  const mime = MIME[path.extname(sub)] ?? "application/octet-stream";
  return `  ["${sub}", { data: Buffer.from("${b64}", "base64"), mime: "${mime}" }]`;
});

const output = `// Auto-generated — DO NOT EDIT
// Generated by packages/cli/scripts/generate-ui-bundle.ts.
// NO COMMITEAR esta versión poblada: al repo sólo va el stub vacío. CI lo
// verifica (.github/workflows/ci.yml, job "guard").
export const embeddedUI = new Map<string, { data: Buffer; mime: string }>([\n${entries.join(",\n")}\n]);\n`;

writeFileSync(outFile, output);

const totalSize = files.reduce((sum, { full }) => sum + statSync(full).size, 0);
console.log(`✅ UI bundle: ${files.length} archivos (${(totalSize / 1024 / 1024).toFixed(1)} MB) → ${outFile}`);
